using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace AionGames.SimpleAnimatorPackage {
    [CreateAssetMenu(fileName = "AnimationLayerList", menuName = "Simple Animator/AnimationLayerList")]
	public class AnimationLayerList : ScriptableObject {
		[HideInInspector]
		public bool isEdited = true;
		[HideInInspector]
		public AnimatorController animatorController;
		[Box("Editing is not supported during runtime", MessageType.Warning)]
		[ReadOnly]
		public string id;
		public AnimationLayer[] layers;
		
		private string dataDirectory;
		
		private int previousLayerCount = 0;

		private void OnValidate(){
			//Generate id
			if (string.IsNullOrEmpty(id)){
				id = Guid.NewGuid().ToString();
			}
			
			//Default value
			if (layers.Length > previousLayerCount) {
				for (int i = previousLayerCount; i < layers.Length; i++) {
					if (layers[i] != null)
						layers[i].weight = 1f;
				}
				previousLayerCount = layers.Length;
			}

			if (layers.Length < previousLayerCount) {
				previousLayerCount = layers.Length;
			}

			//
			isEdited = true;
		}

		public static void ClearForder(string directory){
			string[] files = AssetDatabase.FindAssets("", new[] { directory });
			foreach (string file in files){
				string filePath = AssetDatabase.GUIDToAssetPath(file);
				AssetDatabase.DeleteAsset(filePath);
			}
		}

		// Clean up old assets
		public static void CleanupFolders(){
			string dataDirectory = SimpleAnimator.getDirectory() + "/AutoGenerated";

			// If the directory does not exist, exit
			if (!AssetDatabase.IsValidFolder(dataDirectory)){
				return;
			}

			// Get all folders inside 'AutoGenerated'
			string[] subDirectories = Directory.GetDirectories(dataDirectory)
				.Select(Path.GetFileName) // Solo el nombre de la carpeta
				.ToArray();

			// Get all existing ScriptableObjects
			string[] guids = AssetDatabase.FindAssets($"t:{typeof(AnimationLayerList).Name}");
			var validIds = guids.Select(guid => AssetDatabase.LoadAssetAtPath<AnimationLayerList>(
				AssetDatabase.GUIDToAssetPath(guid)).id).ToHashSet();

			bool deleted = false;

			// Check each folder and delete it if it doesn't belong to a valid ScriptableObject
			foreach (string folder in subDirectories){
				if (!validIds.Contains(folder)){
					string fullPath = dataDirectory.TrimEnd('/') + "/" + folder; // Normalizar ruta

					// Delete all files inside the folder
					AssetDatabase.DeleteAsset(fullPath);

					// Check if it still exists and delete it using System.IO
					if (Directory.Exists(fullPath)){
						Directory.Delete(fullPath, true);
					}

					deleted = true;
				}
			}

			if (deleted){
				AssetDatabase.SaveAssets();
				AssetDatabase.Refresh();
			}
		}
		
		public void Clear(){
			dataDirectory = SimpleAnimator.getDirectory() + "/AutoGenerated/" + id;
            
			// Delete the existing dataDirectory directory if it exists
			if (AssetDatabase.IsValidFolder(dataDirectory)){
				ClearForder(dataDirectory);
			} else {
				AssetDatabase.CreateFolder(SimpleAnimator.getDirectory() + "/AutoGenerated", id);
				AssetDatabase.SaveAssets();
				AssetDatabase.Refresh();
			}
		}
		
		// Apply final modifications to the animator controller
		public void ApplyFinalChanges(){
			if (isEdited) {
				GenerateAnimatorController();
			}
		}
		
		public void GenerateAnimatorController(){
			CleanupFolders();
			Clear();
			
			animatorController = AnimatorController.CreateAnimatorControllerAtPath($"{dataDirectory}/Controller.controller");
			animatorController.layers = new AnimatorControllerLayer[0];
			animatorController.parameters = null;

			if (layers == null) return;
            
			for(int i = 0; i < layers.Length; i++){
				AnimationLayer layer = layers[i]; 
				if (layer.name.Trim().Length == 0) continue;
                
				AddLayer(layer);
                    
				AddParameter(layer.name + "_switch", AnimatorControllerParameterType.Int);
				AddParameter(layer.name + "_S1_speed", AnimatorControllerParameterType.Float);
				AddParameter(layer.name + "_S1_mirror", AnimatorControllerParameterType.Bool);
				AddParameter(layer.name + "_S2_speed", AnimatorControllerParameterType.Float);
				AddParameter(layer.name + "_S2_mirror", AnimatorControllerParameterType.Bool);
                
				AddDefStateToAnimator(layer.name + " Default", i);
				AddStateToAnimator(layer.name + " S1", 1, i);
				AddStateToAnimator(layer.name + " S2", 2, i);
			}
           
			for(int i = 0; i < layers.Length; i++){
				AnimationLayer layer = layers[i];
				if (string.IsNullOrEmpty(layer.name)) continue;
				
				AnimatorControllerLayer layerMod = animatorController.layers[i];
				layerMod.syncedLayerIndex = (!layer.sync) ? -1 : layer.syncLayer;
				animatorController.layers[i] = layerMod;
			}
            
			SaveController();
			isEdited = false;
		}
		
		// Save changes to the asset database
        public void SaveController(){
            EditorUtility.SetDirty(animatorController);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
        
        // Create a new animation layer with a state machine
        public void AddLayer(AnimationLayer layer ) {
            AnimatorStateMachine stateMachine = new AnimatorStateMachine();
            stateMachine.name = layer.name;

            AssetDatabase.AddObjectToAsset(stateMachine, animatorController);

            AnimatorControllerLayer newLayer = new AnimatorControllerLayer {
                name = layer.name,
                defaultWeight = layer.weight,
                stateMachine = stateMachine,
                avatarMask = layer.avatarMask,
                blendingMode = layer.blending,
                iKPass = layer.iKPass,
                syncedLayerAffectsTiming = (!layer.sync) ? false : layer.timing,
                syncedLayerIndex = (!layer.sync) ? -1 : layer.syncLayer,
            };
            
            AnimatorControllerLayer[] layers = animatorController.layers;
            ArrayUtility.Add(ref layers, newLayer);
            animatorController.layers = layers;
        }
        
        // Add a new animation state to the Animator Controller
        public void AddStateToAnimator(string stateName, int stateSwitchPosition, int layerIndex) {
            AnimatorStateMachine rootStateMachine = animatorController.layers[layerIndex].stateMachine;

            AnimatorState newState = rootStateMachine.AddState(stateName, 
                new Vector3(300 * ((stateSwitchPosition == 2) ? 1 : -1), 0, 0));

            AnimationClip clip = new AnimationClip { name = stateName };
            newState.motion = clip;
            
            AssetDatabase.CreateAsset(clip, $"{dataDirectory}/{stateName}.anim");

            newState.speedParameterActive = true;
            newState.speedParameter = animatorController.layers[layerIndex].name + "_S" + stateSwitchPosition + "_speed";

            newState.mirrorParameterActive = true;
            newState.mirrorParameter = animatorController.layers[layerIndex].name + "_S" + stateSwitchPosition + "_mirror";

            AnimatorStateTransition transition = rootStateMachine.AddAnyStateTransition(newState);
            transition.hasExitTime = false;
            transition.hasFixedDuration = true;
            transition.duration = 0.25f;
            transition.canTransitionToSelf = false;

            string transitionParameter = animatorController.layers[layerIndex].name + "_switch";
            transition.AddCondition(AnimatorConditionMode.Equals, stateSwitchPosition, transitionParameter);

            MainAnimatorSMB behaviour = ScriptableObject.CreateInstance<MainAnimatorSMB>();
            AssetDatabase.AddObjectToAsset(behaviour, animatorController);
            newState.behaviours = new[] { behaviour };
        }
        
        // Add a default state to the Animator Controller
        public void AddDefStateToAnimator(string stateName, int layerIndex) {
            AnimatorStateMachine rootStateMachine = animatorController.layers[layerIndex].stateMachine;
            AnimatorState newState = rootStateMachine.AddState(stateName, new Vector3(0, -150, 0));
            
            AnimatorStateTransition transition = rootStateMachine.AddAnyStateTransition(newState);
            transition.hasExitTime = false;
            transition.hasFixedDuration = true;
            transition.duration = 0.25f;
            
            string transitionParameter = animatorController.layers[layerIndex].name + "_switch";
            transition.AddCondition(AnimatorConditionMode.Equals, 0, transitionParameter);
        }
        
        // Add a new parameter to the Animator Controller
        public void AddParameter(string paramName, AnimatorControllerParameterType paramType) {
            AnimatorControllerParameter newParam = new AnimatorControllerParameter {
                name = paramName,
                type = paramType
            };
            
            animatorController.AddParameter(newParam);
        }
	}
}